# Generated by Django 5.1 on 2024-08-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
